common: &common
  adapter: postgresql
  username: cowboy
  password: realfolk

development:
  <<: *common
  database: gpanda_development
production:
  <<: *common
  database: gpanda_production
test:
  <<: *common
  database: gpanda_test